# FriendlyChat Codelab

use_frameworks!
platform :ios, '10.0'

target 'ChatMaster' do
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleSignIn'
  pod 'JSQMessagesViewController'
end
